steps:
  # 1. Download .env dari Cloud Storage
  # Ngambil data env yg disimpen di cloud storage pake gsuri
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "gs://tpm-be/.env", ".env"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/giftbouqet-backend", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/giftbouqet-backend"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "giftbouqet-backend",
        "--image",
        "gcr.io/$PROJECT_ID/giftbouqet-backend",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
        "--port",
        "8080",
        "--timeout",
        "900s",
        "--memory",
        "512Mi",
        "--cpu",
        "1",
        "--min-instances",
        "0",
        "--max-instances",
        "10",
      ]

images:
  - "gcr.io/$PROJECT_ID/giftbouqet-backend"

options:
  logging: CLOUD_LOGGING_ONLY
